name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build OpenCollector Script Container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build :latest
        run: docker build -t binkhq/opencollector-on-windows .
      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push binkhq/opencollector-on-windows
